SELECT B.USER_ID,B.NICKNAME, SUM(A.PRICE) AS TOTAL_PRICE
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON B.USER_ID = A.WRITER_ID
WHERE A.STATUS="DONE"
GROUP BY B.USER_ID
HAVING TOTAL_PRICE>=700000
ORDER BY TOTAL_PRICE

